version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Se agrego este commit
      - echo Se agrego este commit2
      - echo Build started on `date`

artifacts:
   files:
     - '**/*'
